import React from "react";

const List3 = (props) => {
  let cla=props.className+" uList";
  return (
    <ul className={cla}>
      <li> khargone</li>
      <li> kishanganj</li>
      <li> kishangarh</li>
      <li> kochi</li>
      <li> kodaikanal</li>
      <li> kolar</li>
      <li> kolhapur</li>
      <li> kolkata</li>
      <li> kollam</li>
      <li> koppal</li>
      <li> korba</li>
      <li> kota</li>
      <li> kotdwar</li>
      <li> kothagudem</li>
      <li> kothamanagalam</li>
      <li> kottakkal</li>
      <li> kottarakkara</li>
      <li> kottayam</li>
      <li> kozhikode</li>
      <li> krishnagiri</li>
      <li> krishnanagar</li>
      <li> kuchaman</li>
      <li> kumbakonam</li>
      <li> kumta</li>
      <li> kundapura</li>
      <li> kurnool</li>
      <li> kurukshetra</li>
      <li> lakhimpur</li>
      <li> lalitpur</li>
      <li> latur</li>
      <li> lonavala</li>
      <li> lonavla</li>
      <li> lucknow</li>
      <li> ludhiana</li>
      <li> machilipatnam</li>
      <li> madanapalle</li>
      <li> madikeri</li>
      <li> madurai</li>
      <li> mahasamund</li>
      <li> mahbubnagar</li>
      <li> malappuram</li>
      <li> malda</li>
      <li> malegaon</li>
      <li> mallapuram</li>
      <li> malout</li>
      <li> mancherial</li>
      <li> mandi-dabwali</li>
      <li> mandi-gobindgarh</li>
      <li> mandsaur</li>
      <li> mandya</li>
      <li> mangaluru</li>
      <li> manipal</li>
      <li> manjeri</li>
      <li> mansa</li>
      <li> markapur</li>
      <li> mathura</li>
      <li> maunath-bhanjan</li>
      <li> mayiladuthurai</li>
      <li> medak</li>
      <li> medinipur</li>
      <li> meerut</li>
      <li> mehsana</li>
      <li> miryalaguda</li>
      <li> mirzapur</li>
      <li> modinagar</li>
      <li> moga</li>
      <li> moodbidri</li>
      <li> moradabad</li>
      <li> morbi</li>
      <li> morbi-2</li>
      <li> morena</li>
      <li> motihari</li>
      <li> mount-abu</li>
      <li> mughalsarai</li>
      <li> muktsar</li>
      <li> mumbai</li>
      <li> munger</li>
      <li> murdeshwar</li>
      <li> mussoorie</li>
      <li> muvattupuzha</li>
      <li> muzaffarnagar</li>
      <li> muzaffarpur</li>
      <li> mysore</li>
      <li> nabadwip</li>
      <li> nadiad</li>
      <li> nagaon</li>
      <li> nagapattinam</li>
      <li> nagda</li>
      <li> nagercoil</li>
      <li> nagpur</li>
      <li> nagur</li>
      <li> nainital</li>
      <li> nalgonda</li>
      <li> namakkal</li>
      <li> nanded</li>
      <li> nandurbar</li>
      <li> nandyal</li>
      <li> nangal</li>
      <li> naraingarh</li>
      <li> narasaraopet</li>
      <li> narnaul</li>
      <li> narwana</li>
      <li> nashik</li>
      <li> nathdwara</li>
      <li> navsari</li>
      <li> neemuch</li>
      <li> nellore</li>
      <li> neyveli</li>
      <li> nipani</li>
      <li> nirmal</li>
      <li> nizamabad</li>
      <li> noida</li>
      <li> noida-1</li>
      <li> north-goa</li>
      <li> ongole</li>
      <li> ooty</li>
      <li> orai</li>
      <li> osmanabad</li>
      <li> pala</li>
      <li> palakkad</li>
      <li> palampur</li>
      <li> palanpur</li>
      <li> pali</li>
      <li> palwal</li>
      <li> panipat</li>
      <li> parbhani</li>
      <li> patan</li>
      <li> pathankot</li>
      <li> patiala</li>
      <li> patna</li>
      <li> perinthalmanna</li>
      <li> phagwara</li>
      <li> phaltan</li>
      <li> pilani</li>
      <li> pilibhit</li>
      <li> pondicherry</li>
    </ul>
  );
};

export default List3;
