import React from "react";

const List1 = (props) => {
  let cla=props.className+" uList";
  return (
    <ul className={cla}>
      <li> abohar</li>
      <li> adilabad</li>
      <li> adityapur</li>
      <li> adoni</li>
      <li> agartala</li>
      <li> agra</li>
      <li> ahmedabad</li>
      <li> ahmednagar</li>
      <li> aizawl-2</li>
      <li> ajmer</li>
      <li> akola</li>
      <li> alappuzha</li>
      <li> aligarh</li>
      <li> allahabad</li>
      <li> alwar</li>
      <li> ambala</li>
      <li> ambikapur</li>
      <li> ambur</li>
      <li> amravati</li>
      <li> amreli</li>
      <li> amritsar</li>
      <li> amroha</li>
      <li> anand</li>
      <li> anantapur</li>
      <li> ankleshwar</li>
      <li> arrah</li>
      <li> asansol</li>
      <li> ashoknagar</li>
      <li> aurangabad</li>
      <li> aurangabad_bihar</li>
      <li> azamgarh</li>
      <li> baddi</li>
      <li> bagalkot</li>
      <li> bagdogra</li>
      <li> bahadurgarh</li>
      <li> bahraich</li>
      <li> bajpe</li>
      <li> balaghat</li>
      <li> balasore</li>
      <li> ballari</li>
      <li> balrampur</li>
      <li> balurghat</li>
      <li> bangalore</li>
      <li> bankura</li>
      <li> banswara</li>
      <li> bantwal</li>
      <li> bapatlachirala</li>
      <li> baraut</li>
      <li> bardhaman</li>
      <li> bardoli</li>
      <li> bareilly</li>
      <li> barnala</li>
      <li> barshi</li>
      <li> basirhat</li>
      <li> basti</li>
      <li> batala</li>
      <li> bathinda</li>
      <li> beawar</li>
      <li> beed</li>
      <li> begusarai</li>
      <li> belgaum</li>
      <li> berhampore</li>
      <li> berhampur</li>
      <li> bettiah</li>
      <li> betul</li>
      <li> bhadrachalam</li>
      <li> bhadravati</li>
      <li> bhagalpur</li>
      <li> bhandara</li>
      <li> bharabanki</li>
      <li> bharatpur</li>
      <li> bharuch</li>
      <li> bhatapara</li>
      <li> bhatkal</li>
      <li> bhavnagar</li>
      <li> bhilai</li>
      <li> bhilwara</li>
      <li> bhimavaram</li>
      <li> bhind</li>
      <li> bhiwadi</li>
      <li> bhiwani</li>
      <li> bhopal</li>
      <li> bhubaneswar</li>
      <li> bhuj</li>
      <li> bidar</li>
      <li> biharsharif</li>
      <li> bijapur</li>
      <li> bijnor</li>
      <li> bikaner</li>
      <li> bilaspur</li>
      <li> bina</li>
      <li> bodhan-rural</li>
      <li> bokaro</li>
      <li> bolpur</li>
      <li> bongaigaon</li>
      <li> bongaon</li>
      <li> botad</li>
      <li> budaun</li>
      <li> budhwal</li>
      <li> bulandshahr</li>
      <li> buldana</li>
      <li> bundi</li>
      <li> burhanpur</li>
      <li> buxar</li>
      <li> central-goa</li>
      <li> chalakkudy</li>
      <li> chalisgaon</li>
      <li> chandigarh</li>
      <li> chandrapur</li>
      <li> changanasherry</li>
      <li> charkhi-dadri</li>
      <li> chengannur</li>
      <li> chennai</li>
      <li> cherthala</li>
      <li> chhapra</li>
      <li> chhatarpur</li>
      <li> chhindwara</li>
      <li> chikhli</li>
      <li> chikkaballapur</li>
      <li> chikmagalur</li>
      <li> chilakaluripet</li>
      <li> chitradurga</li>
      <li> chittoor</li>
      <li> chittorgarh</li>
      <li> churu</li>
      <li> coimbatore</li>
      <li> cooch-behar</li>
      <li> cuddalore</li>
      <li> cuttack</li>
      <li> dabhoi</li>
      <li> dabra</li>
      <li> dahanu</li>
      <li> dahod</li>
      <li> damoh</li>
      <li> darbhanga</li>
      <li> darjeeling</li>
    </ul>
  );
};

export default List1;
