import React from "react";

const List4 = (props) => {
  let cla=props.className+" uList";
  return (
    <ul className={cla}>
      <li> porbandar</li>
      <li> proddatur</li>
      <li> pudukkottai</li>
      <li> pune</li>
      <li> puri</li>
      <li> purnea</li>
      <li> purulia</li>
      <li> puttur</li>
      <li> rae-bareli</li>
      <li> raichur</li>
      <li> raiganj</li>
      <li> raigarh</li>
      <li> raipur</li>
      <li> rajahmundry</li>
      <li> rajapalayam</li>
      <li> rajkot</li>
      <li> rajnandgaon</li>
      <li> ramagundam</li>
      <li> ramanathapuram</li>
      <li> ramgarh</li>
      <li> rampur</li>
      <li> ranchi</li>
      <li> rangpo</li>
      <li> ranibennur</li>
      <li> raniganj</li>
      <li> ratlam</li>
      <li> ratnagiri</li>
      <li> rayachoty</li>
      <li> rewa</li>
      <li> rewari</li>
      <li> rishikesh</li>
      <li> rohtak</li>
      <li> roorkee</li>
      <li> ropar</li>
      <li> rourkela</li>
      <li> rudrapur</li>
      <li> sagar</li>
      <li> sagara</li>
      <li> saharanpur</li>
      <li> saharsa</li>
      <li> salem</li>
      <li> samastipur</li>
      <li> sambalpur</li>
      <li> sambhal</li>
      <li> sangamner</li>
      <li> sangaria</li>
      <li> sangli</li>
      <li> sangrur</li>
      <li> sardarshahar</li>
      <li> sasaram</li>
      <li> satara</li>
      <li> satna</li>
      <li> sawai-madhopur</li>
      <li> sehore</li>
      <li> seoni</li>
      <li> shahjahanpur</li>
      <li> shillong</li>
      <li> shimla</li>
      <li> shivamogga</li>
      <li> shivpuri</li>
      <li> shrirampur</li>
      <li> siddipet</li>
      <li> sikar</li>
      <li> silchar</li>
      <li> siliguri</li>
      <li> sindhanur</li>
      <li> singrauli</li>
      <li> sirohi</li>
      <li> sirsa</li>
      <li> sirsi</li>
      <li> sitapur</li>
      <li> sivakasi</li>
      <li> sivasagar</li>
      <li> siwan</li>
      <li> solan</li>
      <li> solapur</li>
      <li> sonipat</li>
      <li> south-goa</li>
      <li> sri-ganganagar</li>
      <li> srikakulam</li>
      <li> sultanpur</li>
      <li> surat</li>
      <li> suratgarh</li>
      <li> surendranagar-dudhrej</li>
      <li> suryapet</li>
      <li> tadepalligudem</li>
      <li> tadpatri</li>
      <li> taliparamba</li>
      <li> tamluk</li>
      <li> tanuku</li>
      <li> tarn-taran-sahib</li>
      <li> tezpur</li>
      <li> thalassery</li>
      <li> thanjavur</li>
      <li> theni</li>
      <li> thiruvalla</li>
      <li> thiruvallur</li>
      <li> thiruvananthapuram</li>
      <li> thodupuzha</li>
      <li> thoothukudi</li>
      <li> thrissur</li>
      <li> tinsukia</li>
      <li> tiptur</li>
      <li> tirunelveli</li>
      <li> tirupati</li>
      <li> tirupur</li>
      <li> tiruvannamalai</li>
      <li> tohana</li>
      <li> tonk</li>
      <li> trichy</li>
      <li> tumakuru</li>
      <li> tuni</li>
      <li> udaipur</li>
      <li> udgir</li>
      <li> ujjain</li>
      <li> uluberia</li>
      <li> unnao</li>
      <li> vadodara</li>
      <li> valsad</li>
      <li> vapi</li>
      <li> varanasi</li>
      <li> vellore</li>
      <li> veraval</li>
      <li> vidisha</li>
      <li> vijayawada</li>
      <li> viluppuram</li>
      <li> virudhunagar</li>
      <li> vizag</li>
      <li> vizianagaram</li>
      <li> vyara</li>
      <li> waidhan</li>
      <li> warangal</li>
      <li> wardha</li>
      <li> yamuna-nagar</li>
      <li> yavatmal</li>
    </ul>
  );
};

export default List4;
