import React from "react";

const List2 = (props) => {
  let cla=props.className+" uList";

  return (
    <ul className={cla}>
      <li> datia</li>
      <li> dausa</li>
      <li> davanagere</li>
      <li> dehradun</li>
      <li> dehri</li>
      <li> delhi</li>
      <li> deoghar</li>
      <li> dewas</li>
      <li> dhamtari</li>
      <li> dhanbad</li>
      <li> dhar</li>
      <li> dharamshala</li>
      <li> dharmapuri</li>
      <li> dharwad</li>
      <li> dhule</li>
      <li> dibrugarh</li>
      <li> digha</li>
      <li> dindigul</li>
      <li> doddaballapura</li>
      <li> duliajan</li>
      <li> durgapur</li>
      <li> eluru</li>
      <li> erode</li>
      <li> etawah</li>
      <li> faizabad</li>
      <li> faridabad</li>
      <li> faridkot</li>
      <li> farrukhabad</li>
      <li> fatehabad</li>
      <li> fatehgarh-sahib</li>
      <li> fatehpur</li>
      <li> fazilka</li>
      <li> firozabad</li>
      <li> firozpur</li>
      <li> gadag-betigeri</li>
      <li> gadwal</li>
      <li> gandhidham</li>
      <li> gangawati</li>
      <li> gangtok-2</li>
      <li> gaya</li>
      <li> gharaunda</li>
      <li> giridih</li>
      <li> godhra</li>
      <li> gohana</li>
      <li> gokak</li>
      <li> gokarna</li>
      <li> gonda</li>
      <li> gondal</li>
      <li> gondia</li>
      <li> gopalganj</li>
      <li> gorakhpur</li>
      <li> gudivada</li>
      <li> guna</li>
      <li> guntakal</li>
      <li> guntur</li>
      <li> gurdaspur</li>
      <li> gurgaon</li>
      <li> guwahati</li>
      <li> gwalior</li>
      <li> habra</li>
      <li> haldia</li>
      <li> haldwani</li>
      <li> halol</li>
      <li> hampi</li>
      <li> hansi</li>
      <li> hanumangarh</li>
      <li> hapur</li>
      <li> hardoi</li>
      <li> haridwar</li>
      <li> hassan</li>
      <li> himmatnagar</li>
      <li> hinganghat</li>
      <li> hisar</li>
      <li> hoshangabad</li>
      <li> hoshiarpur</li>
      <li> hospet</li>
      <li> hubli</li>
      <li> hyderabad</li>
      <li> imphal</li>
      <li> indore</li>
      <li> irinjalakuda</li>
      <li> itanagar</li>
      <li> itarsi</li>
      <li> jabalpur</li>
      <li> jagdalpur</li>
      <li> jagraon</li>
      <li> jagtial</li>
      <li> jahanabad</li>
      <li> jaigaon</li>
      <li> jaipur</li>
      <li> jalandhar</li>
      <li> jalgaon</li>
      <li> jalna</li>
      <li> jalpaiguri</li>
      <li> jammu</li>
      <li> jamnagar</li>
      <li> jamshedpur</li>
      <li> janjgir</li>
      <li> jaunpur</li>
      <li> jhalawar</li>
      <li> jhansi</li>
      <li> jhunjhunu</li>
      <li> jind</li>
      <li> jodhpur</li>
      <li> jorhat</li>
      <li> junagadh</li>
      <li> kadapa</li>
      <li> kadiri</li>
      <li> kaithal</li>
      <li> kakinada</li>
      <li> kalaburagi</li>
      <li> kalady</li>
      <li> kamareddy</li>
      <li> kanchrapara</li>
      <li> kanker</li>
      <li> kannauj</li>
      <li> kannur</li>
      <li> kanpur</li>
      <li> kanyakumari</li>
      <li> kapurthala</li>
      <li> karad</li>
      <li> karaikkudi</li>
      <li> karimnagar</li>
      <li> karnal</li>
      <li> karunagappaly</li>
      <li> karur</li>
      <li> karwar</li>
      <li> kashipur</li>
      <li> katihar</li>
      <li> katni</li>
      <li> kavali</li>
      <li> kayamkulam</li>
      <li> khammam</li>
      <li> khandwa</li>
      <li> khanna</li>
      <li> kharagpur</li>
    </ul>
  );
};

export default List2;
